exports.registerUser = require('./registerUser.validator')
exports.loginUser = require('./loginUser.validator')
exports.updateUserById = require('./updateUserById.validator')
exports.updateUserByToken = require('./updateUserByToken.validator')
exports.removeUserById = require('./removeUserById.validator')
exports.removeUserByToken = require('./removeUserByToken.validator')