exports.getUserById = require('./getUserById.controller'),
exports.getUserProfile = require('./getUserProfile.controller'),
exports.listAllUsers = require('./listAllUsers.controller'),
exports.loginUser = require('./loginUser.controller'),
exports.registerUser = require('./registerUser.controller'),
exports.removeUser = require('./removeUser.controller'),
exports.updateUser = require('./updateUserProfile.controller'),
exports.updateUserProfile = require('./updateUserProfile.controller'),